language: elixir

matrix:
  include:
    - otp_release: 20.0
      elixir: 1.6

    - otp_release: 20.0
      elixir: 1.7

    - otp_release: 20.0
      elixir: 1.8

    - otp_release: 20.0
      elixir: 1.9

env:
  global:
    - MIX_ENV=test

sudo: true

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y

install:
  - mix local.rebar --force
  - mix local.hex --force
  - source $HOME/.cargo/env

script:
  - source $HOME/.cargo/env
  - cargo test
  - cd rustler_mix && mix do deps.get, test && cd -
  - cd rustler_tests && mix do deps.get, test && cd -
