#sudo: required
language: c
#language: rust
before_script:
  - curl -O https://raw.githubusercontent.com/spawngrid/kerl/master/kerl
  - chmod a+x kerl
  - ./kerl list releases
  - ./kerl list builds
  - ./kerl list installations
  - ./kerl build 17.5
