#sudo: required
#language: c
language: rust
before_script:
  - curl -O https://raw.githubusercontent.com/spawngrid/kerl/master/kerl
  - chmod a+x kerl
  - ./kerl update releases
  - ./kerl list releases
  - ./kerl list installations
  - ./kerl build 17.5 erlang-17.5
  - ./kerl install && ./kerl cleanup

branches:
  only:
    - master
