#sudo: required
#language: c
language: rust

env:
  global:
    - INSTALL_DIR=%{TRAVIS_BUILD_DIR}

before_script:
  - curl -O https://raw.githubusercontent.com/spawngrid/kerl/master/kerl
  - chmod a+x kerl
  - pwd
  - ./kerl update releases
  - ./kerl list releases
  - ./kerl list installations
  - ./kerl build 17.5 erlang-17.5
  - ./kerl list builds
  - ./kerl install erlang-17.5 %{INSTALL_DIR}
  - chmod a+x %{INSTALL_DIR}/activate 
  - %{INSTALL_DIR}/activate
  - ./kerl cleanup all
  - ./kerl list installations
  - ./kerl active
branches:
  only:
    - master
