[package]
name = "rustler"
description = "Safe Rust wrappers for creating Erlang NIF functions"
repository = "https://github.com/hansihe/Rustler"
version = "0.6.0"
authors = ["Hansihe <me@hansihe.com>"]
license = "BSD-2-Clause"

[dependencies]
ruster_unsafe = ">=0.2"
libc = ">=0.1"
lazy_static = "0.1.*"
