[package]
name = "erlang_nif-sys"
version = "0.4.1"
authors = ["Daniel Goertzen <daniel.goertzen@gmail.com>"]
description = "Create Erlang NIF modules in Rust using the C NIF API."
documentation = "http://goertzenator.github.io/erlang_nif-sys/erlang_nif-sys/index.html"
repository = "https://github.com/goertzenator/erlang_nif-sys"
license = "MIT/Apache-2.0"
keywords = ["FFI", "Erlang", "NIF"]

build = "build.rs"

[build-dependencies]
libc = "0.2"

[dependencies]
libc = "0.2"
