[package]
name = "erlang_nif-sys"
version = "0.6.0-pre"
authors = ["Daniel Goertzen <daniel.goertzen@gmail.com>"]
description = "Create Erlang NIF modules in Rust using the C NIF API."
documentation = "http://goertzenator.github.io/erlang_nif-sys/erlang_nif_sys/index.html"
repository = "https://github.com/goertzenator/erlang_nif-sys"
license = "MIT/Apache-2.0"
keywords = ["FFI", "Erlang", "NIF"]

build = "build.rs"

categories = ["external-ffi-bindings"]


[badges]
travis-ci = { repository = "https://github.com/goertzenator/erlang_nif-sys" }
appveyor  = { repository = "https://github.com/goertzenator/erlang_nif-sys" }

[dependencies]
unreachable = "0.1"

[dev-dependencies]
walkdir = "1.0"
itertools = "0.5"
cargo-erlangapp = "0.1"

[package.metadata.release]
upload-doc = true
