[package]
name = "rustler_codegen"
description = "Compiler plugin for Rustler"
repository = "https://github.com/hansihe/Rustler/tree/master/rustler_codegen"
version = "0.7.1"
authors = ["Hansihe <hansihe@hansihe.com>"]
license = "BSD-2-Clause"

[lib]
plugin = true

[dependencies]
easy-plugin = "0.3.0"
aster = "0.14.0"

#[dependencies.aster]
#path = "../../rustler_vendor/aster/"
