[package]
name = "rustler_codegen"
description = "Compiler plugin for Rustler"
repository = "https://github.com/hansihe/Rustler/tree/master/rustler_codegen"
version = "0.12.0"
authors = ["Hansihe <hansihe@hansihe.com>"]
license = "BSD-2-Clause"

[lib]
plugin = true

[features]
default = ["with-syntex"]
with-syntex = [
    "syntex",
    "syntex_syntax",
]

[dependencies]
syntex = { version = "0.*", optional = true }
syntex_syntax = { version = "0.*", optional = true }

syn = { version = "=0.9", features = ["aster", "visit"] }
quote = "=0.3"
