[package]
name = "rustler_codegen"
description = "Compiler plugin for Rustler"
repository = "https://github.com/hansihe/Rustler/tree/master/rustler_codegen"
version = "0.10.0"
authors = ["Hansihe <hansihe@hansihe.com>"]
license = "BSD-2-Clause"
build = "build.rs"

[lib]
plugin = true

[features]
default = ["with-syntex"]
with-syntex = [
    "synthax/syntex",
    "easy-plugin/stable",
    "syntex",
    "syntex_syntax",
    "aster/with-syntex",
]

[build-dependencies]
easy-plugin = "=0.8.0"
synthax = "0.2.0"

[dependencies]
easy-plugin = "=0.8.0"
aster = "=0.22.0"
synthax = "0.2.0"

syntex = { version = "^0.39.0", optional = true }
syntex_syntax = { version = "^0.39.0", optional = true }
